name: flutter_jvtd_http
description: 聚通达网络请求框架
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # https://pub.dartlang.org/packages/dio
  # Dart的一个强大的Http客户端，支持拦截器、全局配置、FormData、请求取消、文件下载、超时等。
  dio: ^2.0.7
  mime: ^0.9.6+2
  meta: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
